import 'package:al3yadah_app/core/helpers/dimensions.dart';
import 'package:al3yadah_app/core/models/patient.dart';
import 'package:al3yadah_app/core/models/shoulder.dart';
import 'package:al3yadah_app/view/home/widgets/patient_card.dart';
import 'package:flutter/material.dart';

class PatientList extends StatelessWidget {
  PatientList({super.key});

  List<Patient> patients = [
    Patient(
      name: 'Alice Johnson',
      age: 32,
      occupation: 'Teacher',
      medicalRef: '654321',
      weight: 65,
      chiefComplaint: 'Back Pain',
      course: 'Chiropractic Care',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'Previous lower back injury',
        place: 'Clinic B',
        vas: 'Moderate',
        palpation: 'Tender at the lumbar region',
        flexionNote: 'Limited flexion',
        flexionNum: 90,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 60,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Positive impingement sign',
        apprehension: '+ve',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Muscular strain',
        dateTime: DateTime.now(),
      ),
    ),
    Patient(
      name: 'Bob Smith',
      age: 28,
      occupation: 'Software Developer',
      medicalRef: '987654',
      weight: 70,
      chiefComplaint: 'Knee Pain',
      course: 'Orthopedic Consultation',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'Previous knee injury while playing sports',
        place: 'Clinic C',
        vas: 'Severe',
        palpation: 'Tender at the patellar region',
        flexionNote: 'Limited flexion',
        flexionNum: 90,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 60,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Negative impingement sign',
        apprehension: 'notdone',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Meniscal injury',
        dateTime: DateTime.now(),
      ),
    ),
    Patient(
      name: 'Catherine Brown',
      age: 35,
      occupation: 'Dentist',
      medicalRef: '123987',
      weight: 68,
      chiefComplaint: 'Neck Pain',
      course: 'Physical Therapy',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'Sitting long hours at work',
        place: 'Clinic D',
        vas: 'Mild',
        palpation: 'Tender at the cervical region',
        flexionNote: 'Limited flexion',
        flexionNum: 30,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 60,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Negative impingement sign',
        apprehension: 'notdone',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Cervical strain',
        dateTime: DateTime.now(),
      ),
    ),
    Patient(
      name: 'Daniel Wilson',
      age: 40,
      occupation: 'Architect',
      medicalRef: '234567',
      weight: 75,
      chiefComplaint: 'Elbow Pain',
      course: 'Physical Therapy',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'No significant history',
        place: 'Clinic E',
        vas: 'Moderate',
        palpation: 'Tender at the lateral epicondyle',
        flexionNote: 'Limited flexion',
        flexionNum: 100,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 60,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Negative impingement sign',
        apprehension: 'notdone',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Lateral Epicondylitis',
        dateTime: DateTime.now(),
      ),
    ),
    Patient(
      name: 'Eva Taylor',
      age: 30,
      occupation: 'Graphic Designer',
      medicalRef: '345678',
      weight: 55,
      chiefComplaint: 'Wrist Pain',
      course: 'Orthopedic Consultation',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'Repetitive motion injury',
        place: 'Clinic F',
        vas: 'Severe',
        palpation: 'Tender at the wrist joint',
        flexionNote: 'Limited flexion',
        flexionNum: 60,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 45,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Positive impingement sign',
        apprehension: '+ve',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Wrist Sprain',
        dateTime: DateTime.now(),
      ),
    ),
    Patient(
      name: 'Frank Turner',
      age: 45,
      occupation: 'Accountant',
      medicalRef: '876543',
      weight: 80,
      chiefComplaint: 'Ankle Pain',
      course: 'Physical Therapy',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'Previous ankle injury',
        place: 'Clinic G',
        vas: 'Moderate',
        palpation: 'Tender at the lateral malleolus',
        flexionNote: 'Limited flexion',
        flexionNum: 45,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 30,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Negative impingement sign',
        apprehension: 'notdone',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Ankle Sprain',
        dateTime: DateTime.now(),
      ),
    ),
    Patient(
      name: 'Grace Clark',
      age: 38,
      occupation: 'Nurse',
      medicalRef: '234567',
      weight: 70,
      chiefComplaint: 'Hip Pain',
      course: 'Orthopedic Consultation',
      presentedArea: 'Shoulder',
      shoulder: Shoulder(
        cervicalFree: true,
        history: 'Previous hip injury',
        place: 'Clinic H',
        vas: 'Severe',
        palpation: 'Tender at the hip joint',
        flexionNote: 'Limited flexion',
        flexionNum: 60,
        extensionNote: 'Normal extension',
        extensionNum: 2,
        abdNote: 'Painful abduction',
        abdNum: 45,
        erNote: 'Normal external rotation',
        erNum: 45,
        irNote: 'Limited internal rotation',
        irNum: 30,
        hawkinsTest: '+ve',
        neerTest: '-v',
        posterior: 'notdone',
        impingementNote: 'Positive impingement sign',
        apprehension: '+ve',
        relocation: 'notdone',
        instabilityNote: 'No signs of instability',
        bellyOff: 'notdone',
        irls: '+ve',
        erls: 'notdone',
        rcTearNote: 'No signs of RC tear',
        scapularAssistanceTest: '+ve',
        scapularRetractionTest: 'notdone',
        acromioTest: '-v',
        obrienTest: '+ve',
        passiveTest: 'notdone',
        modifiedTest: '-v',
        suspectDiagnose: 'Hip Bursitis',
        dateTime: DateTime.now(),
      ),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: ListView.separated(
        physics: const BouncingScrollPhysics(),
        padding: EdgeInsets.zero,
        itemCount: patients.length,
        itemBuilder: (context, index) {
          return PatientCard(patient: patients[index]);
        },
        separatorBuilder: (context, index) => SizedBox(height: 12.height),
      ),
    );
  }
}
