// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjBXq610rG7zUOpsq0StKFbWoLbqHB7Mc',
    appId: '1:1082720907867:web:0c60eb17a96c89a9b5457e',
    messagingSenderId: '1082720907867',
    projectId: 'al3yadah-15d2d',
    authDomain: 'al3yadah-15d2d.firebaseapp.com',
    storageBucket: 'al3yadah-15d2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAIZTR2Qk_JwoPGLbQkcleazygOAnSuY',
    appId: '1:1082720907867:android:89820fe7ee05f763b5457e',
    messagingSenderId: '1082720907867',
    projectId: 'al3yadah-15d2d',
    storageBucket: 'al3yadah-15d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoC0eCygso7jzfBTAEV0xDG2E_Fw9hsDA',
    appId: '1:1082720907867:ios:bafde150a103d9b0b5457e',
    messagingSenderId: '1082720907867',
    projectId: 'al3yadah-15d2d',
    storageBucket: 'al3yadah-15d2d.appspot.com',
    iosBundleId: 'com.example.al3yadahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoC0eCygso7jzfBTAEV0xDG2E_Fw9hsDA',
    appId: '1:1082720907867:ios:ecc3867680200dd6b5457e',
    messagingSenderId: '1082720907867',
    projectId: 'al3yadah-15d2d',
    storageBucket: 'al3yadah-15d2d.appspot.com',
    iosBundleId: 'com.example.al3yadahApp.RunnerTests',
  );
}
